version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    networks:
      - web
    environment:
      - NODE_ENV=development

  mongo:
    build: 
      dockerfile: Dockerfile.mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      - web



  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - web
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
    
    
networks:
  web:
    driver: bridge
