# Usa la imagen oficial de MongoDB
FROM mongo

# Establece las variables de entorno para el usuario root
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=password

# Expone el puerto 27017
EXPOSE 27017

# Comando para iniciar MongoDB
CMD ["mongod"]
